#include <QSettings>
#include "appdef.h"
#include "saveimagedialog.h"
#include "ui_saveimagedialog.h"

/**
* Constructor
*/
SaveImageDialog::SaveImageDialog(QWidget *parent) :
    QDialog(parent),
    m_ui(new Ui::SaveImageDialog)
{
    m_ui->setupUi(this);

    // initialize controls
    QSettings settings;
    m_ui->imageSizeSpinBox->setValue( settings.value("exportAsImage/imageSize", 600).toInt() );
    m_ui->coordinateCheckBox->setChecked( settings.value("exportAsImage/showCoordinate", true).toBool() );
    m_ui->monochromeCheckBox->setChecked( settings.value("exportAsImage/monochrome", false).toBool() );

    QPushButton* button = m_ui->buttonBox->button(QDialogButtonBox::Ok);
    if (button)
        button->setEnabled(false);
}

/**
* Destructor
*/
SaveImageDialog::~SaveImageDialog()
{
    delete m_ui;
}

/**
* changeEvent
* generated by wizard.
*/
void SaveImageDialog::changeEvent(QEvent *e)
{
    QDialog::changeEvent(e);
    switch (e->type()) {
    case QEvent::LanguageChange:
        m_ui->retranslateUi(this);
        break;
    default:
        break;
    }
}

/**
* accept
* ok button was clicked.
*/
void SaveImageDialog::accept(){
    QDialog::accept();

    imageSize      = m_ui->imageSizeSpinBox->value();
    showCoordinate = m_ui->coordinateCheckBox->isChecked();
    monochrome     = m_ui->monochromeCheckBox->isChecked();

    // save control values
    QSettings settings;
    settings.setValue("exportAsImage/imageSize", imageSize);
    settings.setValue("exportAsImage/showCoordinate", showCoordinate);
    settings.setValue("exportAsImage/monochrome", monochrome);
}

/**
* on_fileBrowseButton_clicked
* browse button was clicked.
*/
void SaveImageDialog::on_fileBrowseButton_clicked(){
    // show save dialog.
    QString selectedFilter;
    QString fname = getSaveFileName(this, QString(), QString(),
        tr("PNG image(*.png);;Bitmap image(*.bmp);;JPEG image(*.jpeg *.jpg);;TIFF image(*.tiff *.tif)"),
        &selectedFilter);
    if (fname.isEmpty())
        return;

    // if extension is nothing, add default extension.
    fileInfo.setFile(fname);
    if (fileInfo.suffix().isEmpty()){
        if (selectedFilter.indexOf("*.png") >= 0)
            fileInfo.setFile(fname + ".png");
        else if (selectedFilter.indexOf("*.bmp") >= 0)
            fileInfo.setFile(fname + ".bmp");
        else if (selectedFilter.indexOf("*.jpg") >= 0)
            fileInfo.setFile(fname + ".jpg");
        else if (selectedFilter.indexOf("*.tiff") >= 0)
            fileInfo.setFile(fname + ".tiff");
    }

    m_ui->fileNameEdit->setText( fileInfo.absoluteFilePath() );
}

/**
* on_fileNameEdit_textChanged
* fileName editbox was changed.
*/
void SaveImageDialog::on_fileNameEdit_textChanged(QString str){
    // ok button is disable if file name is empty.
    QPushButton* button = m_ui->buttonBox->button(QDialogButtonBox::Ok);
    if (button == NULL)
        return;
    button->setEnabled(str.isEmpty() == false);
}
